version: 2
jobs:
  go-version-latest:
    docker:
    - image: cimg/go:1.24-node
    resource_class: large
    steps:
    - checkout
    - run: make -f ./Makefile.cross-compiles
    - store_artifacts:
          path: /release/frpc_android_arm64
    - store_artifacts:
          path: /release/frpc_android_arm

workflows:
  version: 2
  build_and_test:
    jobs:
    - go-version-latest
